import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const androidDir = path.join(rootDir, 'android');
const outputDir = path.join(rootDir, 'output');

// Parse CLI args: node scripts/build-mobile.mjs [--url="..."] [--clean]
const args = process.argv.slice(2);
let targetUrl = process.env.TARGET_URL || process.env.NEXT_PUBLIC_APP_URL || 'https://i-reside-capstone.vercel.app/mobile';
let cleanBuild = false;

for (const arg of args) {
  if (arg.startsWith('--url=')) targetUrl = arg.slice(6);
  else if (arg === '--clean') cleanBuild = true;
}

// Normalize trailing slash if needed
if (!targetUrl.endsWith('/mobile') && !targetUrl.endsWith('/mobile/')) {
  if (targetUrl.endsWith('/')) {
    targetUrl += 'mobile';
  } else {
    targetUrl += '/mobile';
  }
}

console.log('\n======================================================');
console.log('📱 iReside Turnkey Android APK Builder');
console.log('======================================================');
console.log(`• Target Endpoint : ${targetUrl}`);
console.log(`• Android Project : ${androidDir}`);
console.log(`• Package Name    : ph.ireside.mobile`);
console.log(`• Artifact Format : Release APK (Signed v2)`);
console.log('======================================================\n');

// 1. Detect Java JDK (Prefer Android Studio JBR if available, or JAVA_HOME)
let javaHome = process.env.JAVA_HOME;
const defaultJbr = 'C:\\Program Files\\Android\\Android Studio\\jbr';

if (!javaHome || !fs.existsSync(javaHome)) {
  if (fs.existsSync(defaultJbr)) {
    javaHome = defaultJbr;
  }
}

if (!javaHome) {
  console.error('❌ Error: JAVA_HOME is not set and Android Studio JBR was not found.');
  process.exit(1);
}

// 2. Detect Android SDK
let androidHome = process.env.ANDROID_HOME;
const localAppData = process.env.LOCALAPPDATA || 'C:\\Users\\JV\\AppData\\Local';
const defaultSdk = path.join(localAppData, 'Android', 'Sdk');

if (!androidHome || !fs.existsSync(androidHome)) {
  if (fs.existsSync(defaultSdk)) {
    androidHome = defaultSdk;
  }
}

if (!androidHome) {
  console.error('❌ Error: Android SDK could not be located.');
  process.exit(1);
}

// Update local.properties in android directory
const localPropertiesPath = path.join(androidDir, 'local.properties');
const escapedSdk = androidHome.replace(/\\/g, '\\\\');
fs.writeFileSync(localPropertiesPath, `## Auto-generated by build-mobile.mjs\nsdk.dir=${escapedSdk}\n`, 'utf8');

// 3. Prepare Environment
const env = {
  ...process.env,
  JAVA_HOME: javaHome,
  ANDROID_HOME: androidHome,
  PATH: `${path.join(javaHome, 'bin')}${path.delimiter}${process.env.PATH}`
};

console.log(`[Builder] Using JDK: ${javaHome}`);
console.log(`[Builder] Using Android SDK: ${androidHome}`);

// 4. Ensure Keystore exists
const keystorePath = path.join(androidDir, 'app', 'ireside-release.jks');
if (!fs.existsSync(keystorePath)) {
  console.log('[Builder] Generating release signing keystore...');
  const keytoolPath = path.join(javaHome, 'bin', process.platform === 'win32' ? 'keytool.exe' : 'keytool');
  const keygenCmd = `"${keytoolPath}" -genkeypair -v -keystore "${keystorePath}" -alias ireside -keyalg RSA -keysize 2048 -validity 10000 -storepass ireside2026 -keypass ireside2026 -dname "CN=iReside Mobile, OU=Engineering, O=iReside, L=Manila, ST=NCR, C=PH"`;
  execSync(keygenCmd, { stdio: 'inherit' });
}

// 5. Build Release APK
const gradlewCmd = process.platform === 'win32' ? 'gradlew.bat' : './gradlew';
const buildTasks = cleanBuild ? 'clean assembleRelease' : 'assembleRelease';
const fullCommand = `${gradlewCmd} ${buildTasks} -PtargetUrl="${targetUrl}"`;

console.log(`\n[Builder] Running Gradle: ${fullCommand}\n`);
execSync(fullCommand, {
  cwd: androidDir,
  env,
  stdio: 'inherit',
  shell: true
});

// 6. Copy output to /output folder
const srcApk = path.join(androidDir, 'app', 'build', 'outputs', 'apk', 'release', 'app-release.apk');
if (!fs.existsSync(srcApk)) {
  console.error(`❌ Build finished but release APK not found at: ${srcApk}`);
  process.exit(1);
}

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const destApkName = 'iReside-v1.0.0-release.apk';
const destApkPath = path.join(outputDir, destApkName);
fs.copyFileSync(srcApk, destApkPath);

// Also copy to public/downloads so it is directly downloadable from the web app
const publicDownloadsDir = path.join(rootDir, 'public', 'downloads');
if (!fs.existsSync(publicDownloadsDir)) {
  fs.mkdirSync(publicDownloadsDir, { recursive: true });
}
fs.copyFileSync(srcApk, path.join(publicDownloadsDir, destApkName));
fs.copyFileSync(srcApk, path.join(publicDownloadsDir, 'iReside-release.apk'));

// Calculate SHA-256 and size
const fileBuffer = fs.readFileSync(destApkPath);
const hashSum = crypto.createHash('sha256').update(fileBuffer).digest('hex');
const stats = fs.statSync(destApkPath);
const sizeMb = (stats.size / (1024 * 1024)).toFixed(2);

console.log('\n======================================================');
console.log('✅ Android Release APK Build Complete!');
console.log('======================================================');
console.log(`• Destination File : ${destApkPath}`);
console.log(`• APK Size         : ${sizeMb} MB (${stats.size.toLocaleString()} bytes)`);
console.log(`• SHA-256 Checksum : ${hashSum}`);
console.log(`• Package Name     : ph.ireside.mobile`);
console.log(`• Target URL       : ${targetUrl}`);
console.log('======================================================');
console.log('\n📱 To install onto a connected physical Android device or emulator:');
console.log(`   adb install "${destApkPath}"\n`);
