import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const androidDir = path.join(rootDir, 'android');
const outputDir = path.join(rootDir, 'output');
const publicDownloadsDir = path.join(rootDir, 'public', 'downloads');

// Parse CLI args: node scripts/build-mobile.mjs [--url="..."] [--clean]
const args = process.argv.slice(2);
let targetUrl = process.env.TARGET_URL || process.env.NEXT_PUBLIC_APP_URL || 'https://i-reside-capstone.vercel.app/mobile';
let cleanBuild = false;

for (const arg of args) {
  if (arg.startsWith('--url=')) targetUrl = arg.slice(6);
  else if (arg === '--clean') cleanBuild = true;
}

// Normalize trailing slash if needed
if (!targetUrl.endsWith('/mobile') && !targetUrl.endsWith('/mobile/')) {
  if (targetUrl.endsWith('/')) {
    targetUrl += 'mobile';
  } else {
    targetUrl += '/mobile';
  }
}

console.log('\n======================================================');
console.log('📱 iReside Capacitor Android APK Builder');
console.log('======================================================');
console.log(`• Target Endpoint : ${targetUrl}`);
console.log(`• Android Project : ${androidDir}`);
console.log(`• Package Name    : ph.ireside.mobile`);
console.log(`• Artifact Formats: Release APK (v1+v2 signed) & Debug APK`);
console.log('======================================================\n');

// 1. Detect Java JDK (Prefer Android Studio JBR if available, or JAVA_HOME)
let javaHome = process.env.JAVA_HOME;
const defaultJbr = 'C:\\Program Files\\Android\\Android Studio\\jbr';

if (!javaHome || !fs.existsSync(javaHome)) {
  if (fs.existsSync(defaultJbr)) {
    javaHome = defaultJbr;
  }
}

if (!javaHome) {
  console.error('❌ Error: JAVA_HOME is not set and Android Studio JBR was not found.');
  process.exit(1);
}

// 2. Detect Android SDK
let androidHome = process.env.ANDROID_HOME;
const localAppData = process.env.LOCALAPPDATA || 'C:\\Users\\JV\\AppData\\Local';
const defaultSdk = path.join(localAppData, 'Android', 'Sdk');

if (!androidHome || !fs.existsSync(androidHome)) {
  if (fs.existsSync(defaultSdk)) {
    androidHome = defaultSdk;
  }
}

if (!androidHome) {
  console.error('❌ Error: Android SDK could not be located.');
  process.exit(1);
}

// Update local.properties in android directory
const localPropertiesPath = path.join(androidDir, 'local.properties');
const escapedSdk = androidHome.replace(/\\/g, '\\\\');
fs.writeFileSync(localPropertiesPath, `## Auto-generated by build-mobile.mjs\nsdk.dir=${escapedSdk}\n`, 'utf8');

// 3. Prepare Environment
const env = {
  ...process.env,
  JAVA_HOME: javaHome,
  ANDROID_HOME: androidHome,
  PATH: `${path.join(javaHome, 'bin')}${path.delimiter}${process.env.PATH}`
};

console.log(`[Builder] Using JDK: ${javaHome}`);
console.log(`[Builder] Using Android SDK: ${androidHome}`);

// 4. Update Capacitor configuration with target URL
const capacitorConfigPath = path.join(rootDir, 'capacitor.config.ts');
if (fs.existsSync(capacitorConfigPath)) {
  let capTs = fs.readFileSync(capacitorConfigPath, 'utf8');
  capTs = capTs.replace(/url:\s*'[^']+'/, `url: '${targetUrl}'`);
  fs.writeFileSync(capacitorConfigPath, capTs, 'utf8');
}

// Ensure assets/capacitor.config.json has the correct server URL
const assetCapConfigDir = path.join(androidDir, 'app', 'src', 'main', 'assets');
if (!fs.existsSync(assetCapConfigDir)) {
  fs.mkdirSync(assetCapConfigDir, { recursive: true });
}
const assetCapConfigPath = path.join(assetCapConfigDir, 'capacitor.config.json');
const capConfigJson = {
  appId: 'ph.ireside.mobile',
  appName: 'iReside',
  webDir: 'mobile/www',
  server: {
    url: targetUrl,
    cleartext: true
  },
  android: {
    allowMixedContent: true,
    captureInput: true,
    webContentsDebuggingEnabled: false
  }
};
fs.writeFileSync(assetCapConfigPath, JSON.stringify(capConfigJson, null, 2), 'utf8');

// Ensure minimal web assets exist in android assets (avoid copying huge public folder)
const assetPublicDir = path.join(assetCapConfigDir, 'public');
if (!fs.existsSync(assetPublicDir)) {
  fs.mkdirSync(assetPublicDir, { recursive: true });
}
const indexHtmlSrc = path.join(rootDir, 'mobile', 'www', 'index.html');
if (fs.existsSync(indexHtmlSrc)) {
  fs.copyFileSync(indexHtmlSrc, path.join(assetPublicDir, 'index.html'));
}

// 5. Ensure Keystore exists
const keystorePath = path.join(androidDir, 'app', 'ireside-release.jks');
if (!fs.existsSync(keystorePath)) {
  console.log('[Builder] Generating release signing keystore...');
  const keytoolPath = path.join(javaHome, 'bin', process.platform === 'win32' ? 'keytool.exe' : 'keytool');
  const keygenCmd = `"${keytoolPath}" -genkeypair -v -keystore "${keystorePath}" -alias ireside -keyalg RSA -keysize 2048 -validity 10000 -storepass ireside2026 -keypass ireside2026 -dname "CN=iReside Mobile, OU=Engineering, O=iReside, L=Manila, ST=NCR, C=PH"`;
  execSync(keygenCmd, { stdio: 'inherit' });
}

// 6. Build Release and Debug APKs via Gradle
const gradlewCmd = process.platform === 'win32' ? 'gradlew.bat' : './gradlew';
const buildTasks = cleanBuild ? 'clean assembleRelease assembleDebug' : 'assembleRelease assembleDebug';
const fullCommand = `${gradlewCmd} ${buildTasks}`;

console.log(`\n[Builder] Running Gradle: ${fullCommand}\n`);
execSync(fullCommand, {
  cwd: androidDir,
  env,
  stdio: 'inherit',
  shell: true
});

// 7. Verify and copy output APKs
const releaseSrcApk = path.join(androidDir, 'app', 'build', 'outputs', 'apk', 'release', 'app-release.apk');
const debugSrcApk = path.join(androidDir, 'app', 'build', 'outputs', 'apk', 'debug', 'app-debug.apk');

if (!fs.existsSync(releaseSrcApk)) {
  console.error(`❌ Build finished but release APK not found at: ${releaseSrcApk}`);
  process.exit(1);
}

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}
if (!fs.existsSync(publicDownloadsDir)) {
  fs.mkdirSync(publicDownloadsDir, { recursive: true });
}

// Copy Release APK
const releaseName = 'iReside-v1.0.0-release.apk';
const destRelease = path.join(outputDir, releaseName);
fs.copyFileSync(releaseSrcApk, destRelease);
fs.copyFileSync(releaseSrcApk, path.join(publicDownloadsDir, releaseName));
fs.copyFileSync(releaseSrcApk, path.join(publicDownloadsDir, 'iReside-release.apk'));

// Copy Debug APK (Direct Universal Sideload fallback)
const debugName = 'iReside-v1.0.0-debug.apk';
const destDebug = path.join(outputDir, debugName);
if (fs.existsSync(debugSrcApk)) {
  fs.copyFileSync(debugSrcApk, destDebug);
  fs.copyFileSync(debugSrcApk, path.join(publicDownloadsDir, debugName));
  fs.copyFileSync(debugSrcApk, path.join(publicDownloadsDir, 'iReside-debug.apk'));
}

// Calculate metadata
const relBuffer = fs.readFileSync(destRelease);
const relHash = crypto.createHash('sha256').update(relBuffer).digest('hex');
const relStats = fs.statSync(destRelease);
const relSizeMb = (relStats.size / (1024 * 1024)).toFixed(2);

console.log('\n======================================================');
console.log('✅ Android APK Build Complete!');
console.log('======================================================');
console.log(`• Release APK      : ${destRelease}`);
console.log(`  Size             : ${relSizeMb} MB (${relStats.size.toLocaleString()} bytes)`);
console.log(`  SHA-256 Checksum : ${relHash}`);

if (fs.existsSync(destDebug)) {
  const dbgBuffer = fs.readFileSync(destDebug);
  const dbgHash = crypto.createHash('sha256').update(dbgBuffer).digest('hex');
  const dbgStats = fs.statSync(destDebug);
  const dbgSizeMb = (dbgStats.size / (1024 * 1024)).toFixed(2);
  console.log(`• Universal Debug  : ${destDebug}`);
  console.log(`  Size             : ${dbgSizeMb} MB (${dbgStats.size.toLocaleString()} bytes)`);
  console.log(`  SHA-256 Checksum : ${dbgHash}`);
}

console.log(`• Package Name     : ph.ireside.mobile`);
console.log(`• Target URL       : ${targetUrl}`);
console.log('======================================================');
console.log('\n📱 To install onto a connected physical Android device:');
console.log(`   adb install "${destRelease}"\n`);
